Removing molecule for integration testing. Switching back to raw install due to constrains and speed

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -52,11 +52,19 @@ jobs:
         with:
           persist-credentials: false
 
-      - name: Install Molecule tooling
-        run: python3 -m pip install --user ansible molecule "molecule-plugins[docker]"
+      - name: Running installation
+        run: ./install.sh
 
-      - name: Add local Python bin to PATH
-        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
+      - name: Verify installation
+        run: ./verify.sh
 
-      - name: Run Molecule tests
-        run: molecule test
+      - name: Test for idempotence
+        run: |
+          trace_file=$(mktemp)
+          ./install.sh | tee -a "${trace_file}"
+          if tail "${trace_file}" | grep -q 'changed=0.*failed=0'; then
+            echo 'Idempotence test: pass'
+          else
+            echo 'Idempotence test: fail'
+            exit 1
+          fi
